# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tapi.proto\x12\x04\x62\x61nk\x1a\x1fgoogle/protobuf/timestamp.proto\"S\n\x0bTransaction\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x02\x12(\n\x04time\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"6\n\x14\x43reateAccountRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"8\n\x15\x43reateAccountResponse\x12\x11\n\taccountId\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"U\n\x12TransactionRequest\x12\x1c\n\x06\x61\x63tion\x18\x01 \x01(\x0e\x32\x0c.bank.Action\x12\x11\n\taccountId\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x02\"U\n\x13TransactionResponse\x12&\n\x0btransaction\x18\x01 \x01(\x0b\x32\x11.bank.Transaction\x12\x16\n\x0e\x61\x63\x63ountBalance\x18\x02 \x01(\x02\"d\n\x0fTransferRequest\x12\x17\n\x0fsourceAccountId\x18\x01 \x01(\t\x12\x17\n\x0ftargetAccountId\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\x02\x12\x10\n\x08password\x18\x04 \x01(\t\";\n\x14\x42\x61nkStatementRequest\x12\x11\n\taccountId\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"P\n\x15\x42\x61nkStatementResponse\x12\'\n\x0ctransactions\x18\x01 \x03(\x0b\x32\x11.bank.Transaction\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x02*K\n\x06\x41\x63tion\x12\x16\n\x12\x41\x43TION_UNSPECIFIED\x10\x00\x12\x12\n\x0e\x41\x43TION_DEPOSIT\x10\x01\x12\x15\n\x11\x41\x43TION_WITHDRAWAL\x10\x02\x32\xa6\x01\n\x10\x43lerkBankService\x12J\n\rCreateAccount\x12\x1a.bank.CreateAccountRequest\x1a\x1b.bank.CreateAccountResponse\"\x00\x12\x46\n\rDoTransaction\x12\x18.bank.TransactionRequest\x1a\x19.bank.TransactionResponse\"\x00\x32\x9b\x01\n\x11\x43lientBankService\x12>\n\x08Transfer\x12\x15.bank.TransferRequest\x1a\x19.bank.TransactionResponse\"\x00\x12\x46\n\tStatement\x12\x1a.bank.BankStatementRequest\x1a\x1b.bank.BankStatementResponse\"\x00\x42\x08Z\x06./bankb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\006./bank'
  _globals['_ACTION']._serialized_start=670
  _globals['_ACTION']._serialized_end=745
  _globals['_TRANSACTION']._serialized_start=52
  _globals['_TRANSACTION']._serialized_end=135
  _globals['_CREATEACCOUNTREQUEST']._serialized_start=137
  _globals['_CREATEACCOUNTREQUEST']._serialized_end=191
  _globals['_CREATEACCOUNTRESPONSE']._serialized_start=193
  _globals['_CREATEACCOUNTRESPONSE']._serialized_end=249
  _globals['_TRANSACTIONREQUEST']._serialized_start=251
  _globals['_TRANSACTIONREQUEST']._serialized_end=336
  _globals['_TRANSACTIONRESPONSE']._serialized_start=338
  _globals['_TRANSACTIONRESPONSE']._serialized_end=423
  _globals['_TRANSFERREQUEST']._serialized_start=425
  _globals['_TRANSFERREQUEST']._serialized_end=525
  _globals['_BANKSTATEMENTREQUEST']._serialized_start=527
  _globals['_BANKSTATEMENTREQUEST']._serialized_end=586
  _globals['_BANKSTATEMENTRESPONSE']._serialized_start=588
  _globals['_BANKSTATEMENTRESPONSE']._serialized_end=668
  _globals['_CLERKBANKSERVICE']._serialized_start=748
  _globals['_CLERKBANKSERVICE']._serialized_end=914
  _globals['_CLIENTBANKSERVICE']._serialized_start=917
  _globals['_CLIENTBANKSERVICE']._serialized_end=1072
# @@protoc_insertion_point(module_scope)
